package bm.b0b0b0.soulHolo.service;

public enum HologramFailure {
    NONE,
    BACKEND_MISSING,
    WORLDGUARD_MISSING,
    NOT_OWNER_REGION,
    NO_APPLICABLE_REGION,
    REGION_LIMIT,
    HOLOGRAM_LIMIT_DENIED,
    LINE_LIMIT,
    LINE_TOO_LONG,
    BLACKLISTED,
    INVALID_NAME,
    NAME_TAKEN,
    NOT_FOUND,
    NOT_OWNED,
    NO_ACTIVE,
    INVALID_LINE,
    CANNOT_EDIT_OWNER_LINE,
    PLAYER_NOT_FOUND,
    OUTSIDE_REGION,
    NO_PERMISSION,
    LINE_EDIT_DENIED,
    POSITION_DENIED,
    INVALID_SETTING,
    SETTING_DENIED,
    GUI_NO_PERMISSION
}
